# Generated by Django 4.2.4 on 2023-08-29 22:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("todos", "0002_todoitem"),
    ]

    operations = [
        migrations.RenameField(
            model_name="todoitem",
            old_name="todo_list",
            new_name="list",
        ),
    ]
